version: "3.9"

services:
  app:
    build: .

  test:
    build:
      context: src
      dockerfile: src/Dockerfile
    expose:
      - 8081:8081
    environment:
      POSTGRES_DATABASE: test_db
      POSTGRES_USER: test_db
      POSTGRES_PASSWORD: test_db
      POSTGRES_HOST: test_db


  test_db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432:5432
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_db
      - POSTGRES_PASSWORD=test_db
      - POSTGRES_PORT=5432

    volumes:
      - ./db:/var/lib/postgresql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
